### ISSUE TITLE
ANR (DISK I/O) because SDK is reading writing on main thread

### ISSUE THREAD

**Issue by kpuneet** [Parsely/parsely-android#6] opened 2016-04-19 14:05 UTC
I raised this issue in the in removing the External Storage Permission but for sanity creating a new issue
The App is crashing because of ANR (DISK I/O) , it is reading and writing on the main thread .
We can't integrate Parsely in the current form , let me know when can you fix it.

Thanks
Puneet

**Comment by emmett9001** [comment] 2016-04-19 15:06
@kpuneet Please test out [this pull request](https://github.com/Parsely/parsely-android/pull/4) with the new parameter as explained [here](https://github.com/Parsely/parsely-android/pull/4#issuecomment-211475691) and let me know if it fixes your issue. Thanks!

**Comment by nseidm1** [comment] 2016-05-09 13:09
@emmett9001 Is this going to be merged into master any time soon? Our management would like us to use this service, but we need a master tested build before we're going to integrate it.

**Comment by amontalenti** [comment] 2016-05-10 13:16
@emmett9001 This is actually a customer request so if you can address this on Friday bugday, that'd be awesome!

**Comment by emmett9001** [comment] 2016-05-10 18:31
@nseidm1 #7 should be merged by Friday, but we don't have confirmation that the change fixes the issue you're experiencing, since we have not been able to replicate it ourselves. If you'd like to wait until the change is in master to do your testing, that's fine.

**Comment by emmett9001** [comment] 2016-05-10 19:34
@nseidm1 @kpuneet Fix #7 has been merged into master. Let us know if you find any other issues using the SDK, and if [current master](https://github.com/Parsely/parsely-android/releases/tag/2.2) fixes your issue. Thanks!

**Comment by hbbtstar** [comment] 2017-10-06 16:28
@nseidm1 @kpuneet this has been open for awhile now and we can't reproduce ANRs with the code- I'm going to go ahead and close this, but if you are still experiencing this please re-open!

**Closed by hbbtstar** 2017-10-06 16:28 UTC
